import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_title': 'Grocery Admin',
      'nav_overview': 'Tổng quan',
      'nav_users': 'Người dùng',
      'nav_stores': 'Cửa hàng',
      'nav_shippers': 'Giao hàng',
      'nav_orders': 'Đơn hàng',
      'nav_delivery': 'Vận chuyển',
      'nav_settings': 'Cài đặt',
      'settings_title': 'Cài đặt hệ thống',
      'settings_account': 'TÀI KHOẢN ADMIN',
      'settings_personal': 'Thông tin cá nhân',
      'settings_security': 'Bảo mật & Mật khẩu',
      'settings_customization': 'TÙY CHỈNH TRẢI NGHIỆM',
      'settings_notifications': 'Thông báo đẩy',
      'settings_dark_mode': 'Giao diện ứng dụng',
      'settings_language': 'Ngôn ngữ hiển thị',
      'settings_support': 'HỖ TRỢ & PHÁP LÝ',
      'settings_about': 'Về ứng dụng',
      'settings_logout': 'ĐĂNG XUẤT TÀI KHOẢN',
      'edit_profile': 'Chỉnh sửa hồ sơ',
      'save_changes': 'LƯU THAY ĐỔI',
      'full_name': 'Họ và tên',
      'dark_mode_on': 'Chế độ tối',
      'dark_mode_off': 'Chế độ sáng',
      'greeting_morning': 'Chào buổi sáng',
      'greeting_afternoon': 'Chào buổi chiều',
      'greeting_evening': 'Chào buổi tối',
      'greeting_welcome_back': 'Chào mừng bạn trở lại',
      'mgmt_users': 'Quản lý Người dùng',
      'mgmt_stores': 'Quản lý Cửa hàng',
      'mgmt_shippers': 'Quản lý Tài xế',
      'mgmt_orders': 'Quản lý Đơn hàng',
      'mgmt_delivery': 'Quản lý Vận chuyển',
      'search_hint': 'Tìm kiếm...',
      'status': 'Trạng thái',
      'revenue': 'Doanh thu',
      'all': 'Tất cả',
      'active': 'Hoạt động',
      'inactive': 'Đã khóa',
      'role': 'Vai trò',
      'order_pending': 'Chờ xử lý',
      'order_confirmed': 'Đã xác nhận',
      'order_picking': 'Chờ lấy',
      'order_delivering': 'Đang giao',
      'order_delivered': 'Hoàn thành',
      'order_cancelled': 'Đã hủy',
      'detail_user': 'Chi tiết người dùng',
      'detail_store': 'Chi tiết cửa hàng',
      'detail_order': 'Chi tiết đơn hàng',
      'cart_details': 'Giỏ hàng chi tiết',
      'order_history': 'Lịch sử đơn hàng',
      'contact_phone': 'Số điện thoại',
      'joined_date': 'Ngày tham gia',
      'password_change': 'Thay đổi mật khẩu',
      'confirm_delete': 'Xác nhận xóa',
      'save': 'Lưu',
      'cancel': 'Hủy',
      'add': 'Thêm mới',
      'password_hint': 'Mật khẩu',
      'no_data': 'Không có dữ liệu',
      'province': 'Tỉnh / Thành phố',
      'district': 'Quận / Huyện',
      'ward': 'Phường / Xã',
      'street': 'Số nhà, tên đường',
      'select_province': 'Chọn Tỉnh / Thành phố',
      'select_ward': 'Chọn Phường / Xã',
      'address_required': 'Vui lòng nhập địa chỉ cụ thể',
      'password_mismatch': 'Mật khẩu xác nhận không khớp',
      'password_same_as_old': 'Mật khẩu mới không được trùng mật khẩu cũ',
      'password_length_error': 'Mật khẩu phải từ 6 ký tự trở lên',
      'fill_all_fields': 'Vui lòng nhập đầy đủ thông tin',
      'login_welcome': 'Chào mừng trở lại!',
      'login_subtitle': 'Đăng nhập vào tài khoản quản trị',
      'sort_by': 'Sắp xếp theo',
      'newest': 'Mới nhất',
      'oldest': 'Cũ nhất',
      'high_to_low': 'Giá cao đến thấp',
      'low_to_high': 'Giá thấp đến cao',
      'confirm_password': 'Xác nhận mật khẩu',
      'old_password': 'Mật khẩu cũ',
      'new_password': 'Mật khẩu mới',
    },
    'en': {
      'app_title': 'Grocery Admin',
      'nav_overview': 'Overview',
      'nav_users': 'Users',
      'nav_stores': 'Stores',
      'nav_shippers': 'Shippers',
      'nav_orders': 'Orders',
      'nav_delivery': 'Delivery',
      'nav_settings': 'Settings',
      'settings_title': 'System Settings',
      'settings_account': 'ADMIN ACCOUNT',
      'settings_personal': 'Personal Information',
      'settings_security': 'Security & Password',
      'settings_customization': 'EXPERIENCE CUSTOMIZATION',
      'settings_notifications': 'Push Notifications',
      'settings_dark_mode': 'App Appearance',
      'settings_language': 'Display Language',
      'settings_support': 'SUPPORT & LEGAL',
      'settings_about': 'About App',
      'settings_logout': 'LOGOUT ACCOUNT',
      'edit_profile': 'Edit Profile',
      'save_changes': 'SAVE CHANGES',
      'full_name': 'Full Name',
      'dark_mode_on': 'Dark Mode',
      'dark_mode_off': 'Light Mode',
      'greeting_morning': 'Good Morning',
      'greeting_afternoon': 'Good Afternoon',
      'greeting_evening': 'Good Evening',
      'greeting_welcome_back': 'Welcome back',
      'mgmt_users': 'User Management',
      'mgmt_stores': 'Store Management',
      'mgmt_shippers': 'Shipper Management',
      'mgmt_orders': 'Order Management',
      'mgmt_delivery': 'Delivery Management',
      'search_hint': 'Search...',
      'status': 'Status',
      'revenue': 'Revenue',
      'all': 'All',
      'active': 'Active',
      'inactive': 'Banned',
      'role': 'Role',
      'order_pending': 'Pending',
      'order_confirmed': 'Confirmed',
      'order_picking': 'Picking up',
      'order_delivering': 'Delivering',
      'order_delivered': 'Delivered',
      'order_cancelled': 'Cancelled',
      'detail_user': 'User Details',
      'detail_store': 'Store Details',
      'detail_order': 'Order Details',
      'cart_details': 'Cart Details',
      'order_history': 'Order History',
      'contact_phone': 'Phone Number',
      'joined_date': 'Joined Date',
      'password_change': 'Change Password',
      'confirm_delete': 'Confirm Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'add': 'Add New',
      'password_hint': 'Password',
      'no_data': 'No Data Available',
      'province': 'Province / City',
      'district': 'District',
      'ward': 'Ward / Commune',
      'street': 'Street name, number',
      'select_province': 'Select Province',
      'select_ward': 'Select Ward',
      'address_required': 'Please enter a specific address',
      'password_mismatch': 'Passwords do not match',
      'password_same_as_old': 'New password cannot be same as old',
      'password_length_error': 'Password must be at least 6 characters',
      'fill_all_fields': 'Please fill all fields',
      'login_welcome': 'Welcome Back!',
      'login_subtitle': 'Sign in to admin account',
      'sort_by': 'Sort By',
      'newest': 'Newest',
      'oldest': 'Oldest',
      'high_to_low': 'Price: High to Low',
      'low_to_high': 'Price: Low to High',
      'confirm_password': 'Confirm Password',
      'old_password': 'Old Password',
      'new_password': 'New Password',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  String byLocale({required String vi, required String en}) {
    return locale.languageCode == 'en' ? en : vi;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['vi', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
